# Generated by Django 5.2 on 2025-04-12 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kahaniya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category_choices', models.TextField(choices=[('A', 'ADULT'), ('F', 'fiction'), ('FT', 'Fantasy'), ('Lv', 'Love_story')], default='A', max_length=30)),
                ('content', models.TextField(max_length=4000)),
                ('blog_image', models.ImageField(blank=True, default='', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kahaniya.author')),
            ],
        ),
    ]
