# Generated by Django 5.2 on 2025-04-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kahaniya', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
