# Generated by Django 5.2 on 2025-04-16 20:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kahaniya', '0003_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
    ]
