# Generated by Django 5.2 on 2025-04-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kahaniya', '0004_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='author',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category_choices',
            field=models.CharField(choices=[('A', 'ADULT'), ('F', 'fiction'), ('FT', 'Fantasy'), ('Lv', 'Love_story')], default='A', max_length=30),
        ),
    ]
