# Generated by Django 5.2 on 2025-04-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kahaniya', '0005_author_email_author_email_notifications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Profile_photo',
            new_name='profile_photo',
        ),
    ]
