# Generated by Django 5.2 on 2025-04-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kahaniya', '0006_rename_profile_photo_author_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
