# Generated by Django 5.2 on 2025-04-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kahaniya', '0008_readerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='readers'),
        ),
    ]
