# Generated by Django 5.2 on 2025-04-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kahaniya', '0014_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='readerprofile',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
