# Generated by Django 5.2 on 2025-04-24 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kahaniya', '0016_alter_follow_author_alter_follow_user'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id'], name='Kahaniya_co_content_2037d7_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='Kahaniya_co_created_9e5da5_idx'),
        ),
        migrations.AddIndex(
            model_name='postlikes',
            index=models.Index(fields=['content_type', 'object_id'], name='Kahaniya_po_content_4814b8_idx'),
        ),
    ]
