# Generated by Django 5.2 on 2025-04-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kahaniya', '0017_comment_kahaniya_co_content_2037d7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
