# Generated by Django 5.2 on 2025-04-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kahaniya', '0018_author_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readerprofile',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
    ]
