# Generated by Django 5.2 on 2025-04-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kahaniya', '0019_author_is_ban_readerprofile_is_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='has_applied_for_author',
            field=models.BooleanField(default=False),
        ),
    ]
