# Generated by Django 5.2 on 2025-04-26 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kahaniya', '0020_author_has_applied_for_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='readerprofile',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kahaniya.author'),
        ),
    ]
