# Generated by Django 5.2 on 2025-04-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kahaniya', '0021_readerprofile_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
