# Generated by Django 5.2 on 2025-04-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kahaniya', '0023_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_author',
        ),
    ]
