# Generated by Django 5.2 on 2025-05-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kahaniya', '0024_remove_author_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
